### PR TITLE
Update Conversion.java

### PR DESCRIPTION
**Pull request by azizalfort**

### CODE REVIEW

**Review by Sylvan1985 — COMMENTED** [review]
The while loop start at line 37 makes me a bit confused( compare the character with string length)

**Review by Zh1bang — COMMENTED** [review]
I think there is a problem in the function breakForConversion that the length of the string may not be used correctly,this cause the numeratorString may have some problem.

**Review by HanyueW-9 — COMMENTED** [review]
The code structure is format well and clean. And most parts are easy to read.

It's best not to use single letters like 'c', 'n', 'd' or 'i' for variable names. Sometimes these characters make the code hard to read. Although there is a comment at the beginning of each letter for what variable, this is not a good habit. Because when you read the following code you may want to return to the beginning to see the definition of these letters and this is a waste of time, especially if your code is long.

Personally, we don't like this way to define a string, char [] number = {' 1 ', '2', '3', '. ', '4', '5', '6'}; This looks very tiring. You can use this form: String number = "123.456". This will make the string very easy to read.

Your code can't tell the plus or minus signs, and if the real numbers are negative, an error will occur.

There is no instruction in README.md. If you can add some instructions about what this code does and which file is inside which folder etc, it will be better.     (This is also what our group needs to improve)

**Comment by saurabhkakade21** [comment]
Readme and license updated and may change as per further requirements and will be notified.

**Review by azizalfort — COMMENTED** [review]
Great

**Pull request merged**
